version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./routes_api.py:/app/routes_api.py
    environment:
      - REDIS_HOST=redis
      - EXCHANGE_RATES_API_KEY=${EXCHANGE_RATES_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-jwt-secret-for-travel-api}
    depends_on:
      - redis
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
