version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: travel_postgres
    restart: always
    environment:
      POSTGRES_USER: RyanKJo
      POSTGRES_PASSWORD: Sontelkulusevski71121
      POSTGRES_DB: travel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: travel_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  flask:
    build: ./backend
    container_name: travel_flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
      
volumes:
  postgres_data:
  redis_data:
