version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: travel_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  flask:
    build: ./backend
    container_name: travel_flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - EXCHANGE_RATES_API_KEY=${EXCHANGE_RATES_API_KEY}

  frontend:
    image: nginx:alpine
    container_name: travel_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
      
volumes:
  redis_data:
